// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma
// Note: dotenv is not needed as Wrangler loads .env automatically
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Enable experimental WASM modules for the seed script


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    //@ts-ignore
    url: process.env["DIRECT_URL"],
  },
});
